language: ruby

addons:
  postgresql: '9.4'
  code_climate:
    repo_token: 38ecdeef4b88402ea8ac832415a671bfe7795b577ca38b6cce156547a6efbe43

cache:
  bundler: true

sudo: false

bundler_args: --jobs=3 --retry=3 --without development

rvm:
  - '2.3.1'

before_script:
  - bundle install --jobs=3 --retry=3 --without development --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rails test

